# Generated by Django 4.2.5 on 2023-10-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=50, verbose_name='Digite seu logradouro')),
                ('numero', models.CharField(max_length=4, verbose_name='Digite o numero de sua residencia')),
                ('bairro', models.CharField(max_length=50, verbose_name='Digite seu bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Digite sua cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Digite seu estado')),
                ('pais', models.CharField(max_length=50, verbose_name='Digite seu país')),
                ('cep', models.CharField(max_length=8, verbose_name='Digite o CEP')),
            ],
        ),
    ]
