# Generated by Django 4.2.5 on 2023-10-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_telefone_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aplic.cliente'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Digite seu nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='Digite seu cpf')),
                ('contato', models.CharField(max_length=50, verbose_name='Digite seu telefone')),
                ('salario', models.CharField(default='R$', max_length=10, verbose_name='Digite seu salario')),
                ('cargo', models.CharField(max_length=50, verbose_name='Digite seu cargo')),
                ('horario', models.CharField(max_length=50, verbose_name='Digite o horario')),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aplic.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='Funcionario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aplic.funcionario'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='Funcionario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aplic.funcionario'),
        ),
    ]
