# Generated by Django 4.2.5 on 2023-10-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_endereco_cliente_funcionario_endereco_funcionario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='Funcionario',
            new_name='funcionario',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='Funcionario',
            new_name='funcionario',
        ),
    ]
