# Generated by Django 4.2.5 on 2023-10-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_alter_endereco_funcionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proventos', models.IntegerField(verbose_name='Mês de referência')),
            ],
        ),
        migrations.AlterField(
            model_name='endereco',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.cliente'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.funcionario'),
        ),
        migrations.CreateModel(
            name='Contracheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_de_referencia', models.IntegerField(verbose_name='Mes de referencia')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.funcionario')),
            ],
        ),
    ]
