# Generated by Django 4.2.5 on 2023-10-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0010_alter_endereco_funcionario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='funcionario',
        ),
    ]
