# Generated by Django 4.2.5 on 2023-10-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0011_remove_endereco_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracheque',
            name='mes_de_referencia',
            field=models.IntegerField(verbose_name='Mês de referência'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Digite seu salario'),
        ),
        migrations.AlterField(
            model_name='verbas',
            name='proventos',
            field=models.IntegerField(verbose_name='Proventos do Mês de referência'),
        ),
    ]
