# Generated by Django 4.2.5 on 2023-10-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0013_telefone_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.funcionario'),
        ),
    ]
