# Generated by Django 4.2.5 on 2023-10-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0014_endereco_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero da Nota Fiscal')),
                ('data', models.DateField(verbose_name='Data da Nota Fiscal')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Nota Fiscal')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de Nota Fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(verbose_name='Digite o CPF')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.IntegerField(verbose_name='Digite o CNPJ')),
                ('razao_social', models.CharField(max_length=50, verbose_name='Digite a Razão Social')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Proprietario')),
                ('cpf', models.IntegerField(verbose_name='Digite o CPF')),
            ],
        ),
        migrations.AddField(
            model_name='verbas',
            name='demonstrativas',
            field=models.IntegerField(default=0, verbose_name='Demonstrativas do Mês de referência'),
        ),
        migrations.AddField(
            model_name='verbas',
            name='descontos',
            field=models.IntegerField(default=0, verbose_name='Descontos do Mês de referência'),
        ),
        migrations.AlterField(
            model_name='verbas',
            name='proventos',
            field=models.IntegerField(default=0, verbose_name='Proventos do Mês de referência'),
        ),
    ]
