# Generated by Django 4.2.5 on 2023-10-12 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0016_contracheque_verbas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default=0, max_length=2, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cliente',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aplic.cliente'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cliente',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aplic.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='razao_social',
            field=models.CharField(max_length=50, verbose_name='Razão Social'),
        ),
    ]
