# Generated by Django 4.2.5 on 2023-10-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0017_remove_pessoafisica_id_remove_pessoajuridica_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.proprietario'),
        ),
    ]
