# Generated by Django 4.2.5 on 2023-10-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0018_pessoajuridica_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='notafiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.notafiscal'),
        ),
    ]
