# Generated by Django 4.2.5 on 2023-10-13 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0020_remove_pessoajuridica_notafiscal_alter_cliente_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'default_related_name': 'pessoafisica'},
        ),
        migrations.AlterModelOptions(
            name='pessoajuridica',
            options={'default_related_name': 'pessoajuridica'},
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cliente_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.cliente'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cliente_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.cliente'),
        ),
    ]
