# Generated by Django 4.2.5 on 2023-10-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0021_alter_pessoafisica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contracheque',
            options={'verbose_name': 'Contra Cheque', 'verbose_name_plural': 'Contra Cheques'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'default_related_name': 'pessoafisica', 'verbose_name': 'Pessoa Física', 'verbose_name_plural': 'Pessoas Físicas'},
        ),
        migrations.AlterModelOptions(
            name='pessoajuridica',
            options={'default_related_name': 'pessoajuridica', 'verbose_name': 'Pessoa Jurídica', 'verbose_name_plural': 'Pessoas Jurídicas'},
        ),
        migrations.AlterModelOptions(
            name='proprietario',
            options={'verbose_name': 'Proprietário', 'verbose_name_plural': 'Proprietários'},
        ),
        migrations.AlterModelOptions(
            name='telefone',
            options={'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
        migrations.AlterModelOptions(
            name='verbas',
            options={'verbose_name': 'Verba', 'verbose_name_plural': 'Verbas'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='verbas',
            name='demonstrativas',
        ),
        migrations.RemoveField(
            model_name='verbas',
            name='descontos',
        ),
        migrations.RemoveField(
            model_name='verbas',
            name='proventos',
        ),
        migrations.AddField(
            model_name='endereco',
            name='tipo',
            field=models.CharField(choices=[('funcionario', 'Funcionário'), ('cliente', 'Cliente')], default='Cliente', max_length=11, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='horario_entrada',
            field=models.TimeField(help_text='Format: HH:MM', null=True, verbose_name='Horário de Entrada'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='horario_saida',
            field=models.TimeField(help_text='Format: HH:MM', null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('funcionario', 'Funcionário'), ('cliente', 'Cliente')], default='cliente', max_length=11, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='verbas',
            name='nome',
            field=models.CharField(default='Verba', max_length=50, verbose_name='Nome da Verba'),
        ),
        migrations.AddField(
            model_name='verbas',
            name='tipo',
            field=models.CharField(choices=[('provento', 'Provento'), ('desconto', 'Desconto'), ('demonstrativa', 'Demonstrativa')], default='provento', max_length=13, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='verbas',
            name='valor',
            field=models.IntegerField(default=0, verbose_name='Valor da Verba'),
        ),
        migrations.AlterField(
            model_name='contracheque',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracheques', to='aplic.funcionario'),
        ),
        migrations.AlterField(
            model_name='contracheque',
            name='verbas',
            field=models.ManyToManyField(related_name='contracheques', to='aplic.verbas'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.cliente'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=50, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=4, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='contato',
            field=models.CharField(max_length=50, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero',
            field=models.IntegerField(verbose_name='Número da Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saída', 'Saída')], max_length=20, verbose_name='Tipo de Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Proprietário'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.cliente'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número de Telefone'),
        ),
    ]
