# Generated by Django 4.2.6 on 2023-10-19 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0024_alter_pessoafisica_cliente_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.proprietario'),
        ),
    ]
