# Generated by Django 4.2.6 on 2023-10-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0027_remove_funcionario_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionario_fotos/', verbose_name='Foto'),
        ),
    ]
